# Generated by Django 5.1.3 on 2024-11-15 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentes',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='agentes',
            name='precio',
        ),
        migrations.AlterField(
            model_name='agentes',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentes', to='agentes.categoria'),
        ),
    ]
